spring:
  datasource:
    url: jdbc:mysql://192.168.13.128/jpa
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#  由此可见jpa底层应用了hibernate的一些功能
    hibernate:
#      更新或者创建数据表结构,根据实体类
      ddl-auto: update
#   显示hibernate操作的语句
    show-sql: true
